# $Id$
---
- name: package install
  package:
    name:
      - python36
    state: latest

- name: pip3 install
  pip:
    name:
      - pip
      - awscli
      - apache-libcloud
      - boto
      - boto3
      - crcmod
      - dnspython
      - netaddr
      - pymysql
    executable: /usr/local/bin/pip3
    state: latest

- name: aws.rc scripts
  template:
    src: "{{ item.path }}"
    dest: "/{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: etc/aws.rc, mode: "0644" }
